### ISSUE TITLE
关于mongo的问题

### ISSUE THREAD

**Issue by flymzero** [lotteryjs/Ten-Minutes-App#2]
今天看到你的项目，对 mongo官方库不太了解，看你的项目是在启动的时候会连接mongo，然后不释放，是不是这样所有的网络请求都是用的是一个数据库连接，（不知道我有没有理解对），那这样高并发会不会卡，网上查一般操作是短连接或者使用连接池，但是网上没找到关于官方库连接池的文章，所以想问问你

**Comment by Kirk-Wang** [comment]
hi, 一般要应对高并发，中间会有一个redis集群的，不会那么快的持久化。

**Comment by Wind4** [comment]
`mongo-go-driver` 内部有连接池，不需要频繁关闭连接。可以通过 `MaxPoolSize` 可以配置连接池大小。

源代码：https://github.com/mongodb/mongo-go-driver/blob/976cd7c625aa8bb4b19ed2cb57d0bac048e91ca9/mongo/client.go#L327
