### ISSUE TITLE
操作能不能更细节一点

### ISSUE THREAD

**Issue by MaxZzyo** [lotteryjs/Ten-Minutes-App#3]
用示例的运行方法 go run .
会报依赖没安装的错误，一下子不知道那么多依赖怎么一次性都装上

**Comment by Kirk-Wang** [comment]
嗯嗯，项目重构中
接下来会用 graphql 去适配这个 demo 的所有 Api
[https://marmelab.com/react-admin-demo/#/](url)

**Comment by MaxZzyo** [comment]
> 嗯嗯，项目重构中
> 接下来会用 graphql 去适配这个 demo 的所有 Api
> [react-admin-demo](https://marmelab.com/react-admin-demo/#/)

我是新学golang，包管理方面一直不是很懂，像这个项目第一次拿到手，有一个go.mod，用go mod命令怎么直接把go.mod里面的依赖全安装上？

**Comment by Kirk-Wang** [comment]
[Go Module](https://www.youtube.com/watch?v=MXjYRrZnHh0)
很不错视频教学，完整讲解包管理方面
